services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run build && npm start"
    ports:
      - 3000:3000
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
    # environment:
    #   MYSQL_HOST: mysql
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: secret
    #   MYSQL_DB: todos

#   mysql:
#     image: mysql:8.0
#     volumes:
#       - todo-mysql-data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: secret
#       MYSQL_DATABASE: todos
#
# volumes:
#   todo-mysql-data:
